-- Create profiles table (extends Supabase auth.users)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  avatar_url text,
  updated_at timestamp with time zone
);

-- Create products table
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price decimal(10,2) not null,
  original_price decimal(10,2),
  image_url text,
  category text,
  platform text,
  region text,
  stock integer default 0,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create orders table
create table public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users,
  guest_email text,
  total_amount decimal(10,2) not null,
  status text default 'pending', -- pending, processing, completed, cancelled
  payment_status text default 'pending',
  payment_method text,
  shipping_address jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create order_items table
create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders not null,
  product_id bigint references public.products,
  product_name text not null,
  quantity integer not null,
  price decimal(10,2) not null,
  player_id text, -- For game top-ups
  server_id text, -- For game top-ups
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Policies

-- Profiles: Users can view and update their own profile
create policy "Public profiles are viewable by everyone." on public.profiles for select using ( true );
create policy "Users can insert their own profile." on public.profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on public.profiles for update using ( auth.uid() = id );

-- Products: Everyone can view active products, only admins can edit (skipping admin check for now, allowing all read)
create policy "Products are viewable by everyone." on public.products for select using ( true );

-- Orders: Users can view their own orders. Guests can't view via API (handled by backend/email).
create policy "Users can view own orders." on public.orders for select using ( auth.uid() = user_id );
create policy "Users can insert own orders." on public.orders for insert with check ( auth.uid() = user_id OR user_id is null );

-- Order Items: Viewable if the parent order is viewable
create policy "Users can view own order items." on public.order_items for select using ( 
  exists ( select 1 from public.orders where orders.id = order_items.order_id and orders.user_id = auth.uid() )
);
create policy "Users can insert own order items." on public.order_items for insert with check ( true ); -- Simplified for demo

-- Insert some sample products
insert into public.products (name, description, price, original_price, category, platform, region, stock) values
('Free Fire 100 Diamonds', 'Top up 100 Diamonds for Free Fire. Instant delivery.', 1.20, 1.50, 'Game Top-up', 'Free Fire', 'Global', 1000),
('Free Fire 520 Diamonds', 'Top up 520 Diamonds for Free Fire. Instant delivery.', 5.50, 6.00, 'Game Top-up', 'Free Fire', 'Global', 1000),
('PUBG Mobile 60 UC', 'Top up 60 UC for PUBG Mobile.', 0.99, 1.10, 'Game Top-up', 'PUBG Mobile', 'Global', 1000),
('Steam Wallet $10', 'Add $10 to your Steam Wallet.', 10.00, 10.00, 'Gift Card', 'Steam', 'Global', 500),
('Google Play $10', 'Google Play Gift Card $10.', 10.00, 10.00, 'Gift Card', 'Google Play', 'US', 500);
