-- Create brands table
CREATE TABLE public.brands (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  icon text,
  description text,
  color text,
  platform text,
  is_featured boolean DEFAULT false,
  product_count integer DEFAULT 0, -- Denormalized count or just static info
  popular_items text[], -- Storing as array of strings for simple display
  delivery_time text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Re-create products table to match new schema
-- First, drop existing if it exists (warning: deletes data, but we are migrating)
DROP TABLE IF EXISTS public.order_items; -- Dependent table
DROP TABLE IF EXISTS public.products;

CREATE TABLE public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id bigint REFERENCES public.brands(id) ON DELETE CASCADE,
  name text NOT NULL,
  description text,
  price decimal(10,2) NOT NULL,
  original_price decimal(10,2),
  discount_percentage integer,
  discount_label text, -- e.g. "5% OFF"
  image_url text, -- Using icon for now if no image
  platform text,
  region text DEFAULT 'Global',
  stock integer DEFAULT 100,
  rating decimal(3,1) DEFAULT 5.0,
  is_popular boolean DEFAULT false,
  delivery_time text,
  category text, -- e.g. "Steam", "Game Top-up"
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Re-create order_items table
CREATE TABLE public.order_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint REFERENCES public.orders(id) NOT NULL,
  product_id bigint REFERENCES public.products(id),
  product_name text NOT NULL,
  quantity integer NOT NULL,
  price decimal(10,2) NOT NULL,
  player_id text,
  server_id text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Enable RLS
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Brands viewable by everyone" ON public.brands FOR SELECT USING (true);
CREATE POLICY "Products viewable by everyone" ON public.products FOR SELECT USING (true);
CREATE POLICY "Order items viewable by owner" ON public.order_items FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.orders WHERE orders.id = order_items.order_id AND orders.user_id = auth.uid())
);
CREATE POLICY "Users can insert own order items" ON public.order_items FOR INSERT WITH CHECK (true);

-- Insert Brands
INSERT INTO public.brands (name, icon, description, color, platform, is_featured, product_count, popular_items, delivery_time) VALUES
('Steam Wallet', '🎮', 'Digital currency for Steam platform. Buy games, DLCs, and in-game items.', '#1b2838', 'Steam', true, 15, ARRAY['$5 Wallet', '$10 Wallet', '$20 Wallet', '$50 Wallet'], 'Instant Delivery'),
('PlayStation Network', '🎯', 'PSN gift cards and codes for PS4/PS5 games, subscriptions, and content.', '#003087', 'PlayStation', true, 12, ARRAY['$10 PSN Card', '$20 PSN Card', '$50 PSN Card'], '1-5 Minutes'),
('Xbox Live', '⚡', 'Microsoft Xbox gift cards and Game Pass subscriptions.', '#107c10', 'Xbox', true, 10, ARRAY['Xbox $10 Gift', 'Xbox $25 Gift', 'Game Pass Ultimate'], 'Instant Delivery'),
('Nintendo eShop', '🎲', 'Nintendo digital codes for Switch games and eShop credit.', '#e60012', 'Nintendo', false, 8, ARRAY['$10 eShop', '$20 eShop', '$35 eShop'], '2-10 Minutes'),
('Apple Gift Cards', '🍎', 'App Store & iTunes cards for apps, music, movies, and subscriptions.', '#a2aaad', 'Apple', true, 20, ARRAY['$15 iTunes', '$25 iTunes', '$50 iTunes'], 'Instant'),
('Google Play', '📱', 'Android app store credit for apps, games, movies, and books.', '#4285f4', 'Google', false, 18, ARRAY['$10 Google Play', '$25 Google Play', '$50 Google Play'], 'Instant'),
('Spotify Premium', '🎵', 'Music streaming subscription with ad-free listening.', '#1db954', 'Spotify', true, 6, ARRAY['1 Month Premium', '3 Months Premium', '1 Year Premium'], '5-15 Minutes'),
('Netflix Gift Cards', '📺', 'Video streaming subscription cards for movies and TV shows.', '#e50914', 'Netflix', false, 7, ARRAY['$30 Netflix', '$60 Netflix'], 'Instant'),
('Amazon Gift Cards', '📦', 'Amazon shopping balance for millions of products.', '#ff9900', 'Amazon', true, 25, ARRAY['$25 Amazon'], '1-3 Minutes'),
('Razer Gold', '🐍', 'Gaming credits and pins for top games and esports titles.', '#44d62c', 'Razer', false, 5, ARRAY['$10 Razer Gold', '$25 Razer Gold'], 'Instant');

-- Insert Products (Procedure to generate sub-products similar to JS logic)
DO $$
DECLARE
    brand_rec RECORD;
    denom INTEGER;
    denominations INTEGER[] := ARRAY[5, 10, 20, 25, 30, 50, 75, 100, 150, 200];
    discounts TEXT[] := ARRAY['5% OFF', '10% OFF', '15% OFF', '20% OFF', '25% OFF'];
    discount_vals INTEGER[] := ARRAY[5, 10, 15, 20, 25];
    delivery_times TEXT[] := ARRAY['Instant', '5 mins', '10 mins', '15 mins'];
    idx INTEGER;
    original_price DECIMAL;
    discounted_price DECIMAL;
    discount_idx INTEGER;
    discount_pct INTEGER;
    discount_str TEXT;
    is_pop BOOLEAN;
BEGIN
    FOR brand_rec IN SELECT * FROM public.brands LOOP
        
        -- Generate 10 products per brand
        FOR idx IN 1..10 LOOP
            denom := denominations[idx];
            discount_idx := ((idx - 1) % 5) + 1;
            discount_pct := discount_vals[discount_idx];
            discount_str := discounts[discount_idx];
            
            original_price := denom::DECIMAL;
            discounted_price := original_price * (1.0 - (discount_pct::DECIMAL / 100.0));
            
            is_pop := idx <= 3;

            INSERT INTO public.products (
                brand_id, name, description, price, original_price, discount_percentage, discount_label,
                platform, is_popular, delivery_time, category, rating
            ) VALUES (
                brand_rec.id,
                brand_rec.name || ' $' || denom,
                brand_rec.description,
                discounted_price,
                original_price,
                discount_pct,
                discount_str,
                brand_rec.platform,
                is_pop,
                delivery_times[((idx - 1) % 4) + 1],
                brand_rec.name,
                (4.5 + random() * 0.5)::DECIMAL(3,1)
            );
        END LOOP;
    END LOOP;
END $$;
